### ISSUE TITLE
Test and document cloud formation process (share clean repo with customer)

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-icap-cloud-formation#18]
1.- test the workflow you can see at https://github.com/k8-proxy/k8-icap-cloud-formation/tree/main/icap-controller/eu-west-3

2.- where it can be involved using
./create-stack.sh eipalloc-03be0f9ffddb671b4 10

![image (3)](https://user-images.githubusercontent.com/70196799/107253680-d9377280-6a36-11eb-8cad-c4b94385c5e3.png)

3.- Document the following:
- we need a diagram for what the cloud formation script will do
- document the changes that will be done in AWS
- document the pre-requisite (for example needing an elastic IP)
- document how to use the scripts above and in general all the process, see also https://github.com/k8-proxy/k8-icap-cloud-formation

**Comment by MaNe2020** [comment]
@GINAGC @Lestat06 @svf97 
here is the diagram 
![image](https://user-images.githubusercontent.com/70108899/107366117-0c810c80-6ade-11eb-8753-289c28bd1135.png)

let me know if you have any fb

**Comment by MaNe2020** [comment]
@aduvukace this is work in progress. 
@svf97 and @Lestat06 are documenting the work, I worked on diagram.

**Comment by Lestat06** [comment]
@aduvukace managed to get access and successfully created stack. starting documenting the changes with @svf97

**Comment by MaNe2020** [comment]
@aduvukace in case @Lestat06 and @svf97 need additional help, I will verify the flow one more time.
At the moment no work done from my side.

**Comment by gurunathg** [comment]
Working on refactoring of repo to have single script for Create and another for Delete which works across all regions.

**Comment by gurunathg** [comment]
Completed refactoring of repo and submitted changes and merged changes to main as part of #37 . @GINAGC  @svf97 Could you please confirm if we can close this issue?

**Comment by GINAGC** [comment]
I will let @svf97 to confirm if testing is done and then we can close it.

**Comment by svf97** [comment]
@gurunathg @GINAGC here's the final PR https://github.com/k8-proxy/k8-icap-cloud-formation/pull/38 that includes all minor adjustments, after approval, we can close this issue

**Comment by gurunathg** [comment]
@svf97 Just had a look at #38. This seems older documentation. Can you please take a look at latest documentation in develop branch

**Comment by svf97** [comment]
@GINAGC main is now up to date

**Comment by GINAGC** [comment]
thank you everyone, closing this issue.
