### ISSUE TITLE
Create multiple cloud formation scripts from the GitHub Readme page

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-icap-cloud-formation#20]
see what was done here: https://github.com/k8-proxy/aws-jmeter-test-engine 

we will share a recording meeting with more details.

**Comment by gurunathg** [comment]
Made required changes as part of #23

**Comment by gurunathg** [comment]
@GINAGC Latest changes for creating stack from Readme is merged to main. Can you please confirm if we can close this issue
