### ISSUE TITLE
Automatically upload latest template to S3 bucket

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-icap-cloud-formation#35]

**Comment by GINAGC** [comment]
@gurunathg where is this documented and video of how it works?

**Comment by gurunathg** [comment]
@GINAGC  Example run which got triggered when pushed: https://github.com/k8-proxy/k8-icap-cloud-formation/runs/1992591724?check_suite_focus=true . I will record a demo video on this and will update document

**Comment by gurunathg** [comment]
@GINAGC  Changes are merged as part of #45 . Please confirm if we can close this
